### ISSUE TITLE
Run headless on a ubuntu server?

### ISSUE THREAD

**Issue by rtmill22** [daveharmon/Southwest-Checkin#10]
I have been trying to modify the code to get this to run headless on a ubuntu 16.04 server but have been unable to get it to work. I think it will run faster in headless mode, does anyone know how to modify the code for this?

**Comment by colacadstink** [comment]
Yeah, you have to add a few lines of code to simulate a screen. I've got it
on my box at home, I'll share it later tonight.

**Comment by colacadstink** [comment]
from pyvirtualdisplay import Display

display = Display(visible=0, size=(800, 600))
display.start()

**Comment by daveharmon** [comment]
Thanks for the heads up @colacadstink. If you Do a PR with your headless script as a new file I would love to include it!

**Comment by colacadstink** [comment]
I created a new command line switch for it instead, -H. See #11 :+1:

**Comment by rtmill22** [comment]
This seems to work on a version with a GUI, any ideas on getting this to work on a server with no GUI or graphics card? Just command line Ubuntu 16.04

**Comment by colacadstink** [comment]
What error do you get when you run this on a purely headless Linux box? I
didn't think the virtual display was dependent on having a running gui.

**Comment by rtmill22** [comment]
See below, I was assuming I was having issues because it wasn't a GUI. I have used selenium with phantomjs with no issues

Traceback (most recent call last):
  File "southwest_checkin.py", line 25, in <module>
    driver = webdriver.Chrome()
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127

**Comment by rtmill22** [comment]
I also usually run on python 3 but am having this error with python 3:

 File "southwest_checkin.py", line 87
    except NoSuchElementException StaleElementReferenceException:
                                                               ^
SyntaxError: invalid syntax

**Comment by colacadstink** [comment]
This is Python 2 code, so you'll definitely get some weirdness if you run this in Python 3.

Do you have Chrome installed? `sudo apt-get install chromium-browser`
Do you have xvfb installed? `sudo apt-get install xvfb`

**Comment by rtmill22** [comment]
Yes I did, i also reinstalled them again and I'm still getting the following error when running as python 2

Traceback (most recent call last):
  File "southwest_checkin.py", line 25, in <module>
    driver = webdriver.Chrome()
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127

**Comment by colacadstink** [comment]
The only other thing I can think of is if the code isn't finding the right version of chromedriver; other than that, I'm honestly stumped here. I'll play around with this when I get home and see if I can duplicate it - you're using [Ubuntu Server 16.04.3 LTE](https://www.ubuntu.com/download/server), yes?

**Comment by rtmill22** [comment]
Yes that is the correct version, thank you, I really appreciate your help!

**Comment by colacadstink** [comment]
Try `sudo apt-get install libgconf-2-4`. I was able to duplicate the problem, and it looks like that fixes it.

**Comment by rtmill22** [comment]
Thanks, I will try it out!

**Comment by daveharmon** [comment]
Can I mark this issue as closed?

**Comment by rtmill22** [comment]
Yes thanks!

**Comment by colacadstink** [comment]
So, uh, @daveharmon, close it then? :stuck_out_tongue:
