### ISSUE TITLE
Use mobile site for check in?

### ISSUE THREAD

**Issue by Stratus3D** [daveharmon/Southwest-Checkin#5]
https://github.com/daveharmon/Southwest-Checkin/blob/f3a9cfe5a0f1ec93f1b1176d8630ee88c3424854/southwest_checkin.py#L28

I've noticed the mobile site (https://mobile.southwest.com/check-in) is much simpler than the regular site. It might be easier if we the script checked in via the mobile site. If you think this is worthwhile I'd be happy to try and create a PR for this.

**Comment by daveharmon** [comment]
That would be interesting, If you'd like to explore it you're more than welcome. I'm not sure if there are differences that may interfere with the web driver.

**Comment by Stratus3D** [comment]
@daveharmon I'd try it, but I'm not really sure how I'd go about testing this. I don't have a flight to check in to right now. Any suggestions?

**Comment by daveharmon** [comment]
I don't unfortunately, maybe next time you have a flight give it a shot. It's not exactly a time-sensitive issue :)
